### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by snorkrat** [jzelinskie/homebrew-duckdns#6]
Not sure where to ask this question, but can I specify multiple domains in the config file?

**Comment by jaredmoody** [comment]
I'm not the author, but looking at the code, yes. In your config file just make `DOMAINS` a comma separated list of your domains, e.g. `DOMAINS=domain1,domain2`

**Comment by jaredmoody** [comment]
#7 updates the readme to demonstrate multiple domains. 

@jzelinskie this issue can be closed.
